server.servlet.contextPath=/darkness
server.port = 2400

logging.level.org.springframework=info
logging.hibernate=DEBUG

# Thymeleaf
spring.thymeleaf.cache = false
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# H2 DB set up
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

# jpa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#H2 dialect sets
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Reactor Netty config
server.netty.max-initial-line-length=65536

# Game Settings
game.max-players=50
