# Generated by Django 4.2.7 on 2026-06-16 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('item_type', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exits', models.JSONField(default=dict)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('safe_zone', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, related_name='rooms', to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=25)),
                ('hp', models.IntegerField(default=100)),
                ('hp_max', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=20)),
                ('mana_max', models.IntegerField(default=20)),
                ('str_stat', models.IntegerField(default=10)),
                ('int_stat', models.IntegerField(default=10)),
                ('wil_stat', models.IntegerField(default=10)),
                ('agi_stat', models.IntegerField(default=10)),
                ('hea_stat', models.IntegerField(default=10)),
                ('cha_stat', models.IntegerField(default=10)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('race', models.CharField(max_length=50)),
                ('game_class', models.CharField(max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('inventory', models.ManyToManyField(through='game.InventoryItem', to='game.item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hp_max', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('money_drop', models.IntegerField()),
                ('exp_drop', models.IntegerField()),
                ('aggressive', models.BooleanField(default=True)),
                ('drops', models.ManyToManyField(blank=True, to='game.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
