# Generated by Django 4.2.18 on 2026-06-22 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('total_rooms', models.IntegerField(default=0)),
                ('total_npcs', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('item_type', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
                ('heal_amount', models.IntegerField(default=0)),
                ('str_bonus', models.IntegerField(default=0)),
                ('int_bonus', models.IntegerField(default=0)),
                ('wil_bonus', models.IntegerField(default=0)),
                ('agi_bonus', models.IntegerField(default=0)),
                ('hea_bonus', models.IntegerField(default=0)),
                ('cha_bonus', models.IntegerField(default=0)),
                ('element', models.CharField(default='physical', max_length=20)),
                ('addiction_chance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hp_max', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('money_drop', models.IntegerField()),
                ('exp_drop', models.IntegerField()),
                ('aggressive', models.BooleanField(default=True)),
                ('npc_type', models.CharField(default='drone', max_length=50)),
                ('respawnable', models.BooleanField(default=True)),
                ('element', models.CharField(default='physical', max_length=20)),
                ('weakness', models.CharField(default='none', max_length=20)),
                ('resistance', models.CharField(default='none', max_length=20)),
                ('drops', models.ManyToManyField(blank=True, to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exits', models.JSONField(default=dict)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('safe_zone', models.BooleanField(default=False)),
                ('zone', models.CharField(default='hub', max_length=100)),
                ('theme', models.CharField(default='urban', max_length=100)),
                ('map_x', models.IntegerField(default=0)),
                ('map_y', models.IntegerField(default=0)),
                ('respawn_npcs', models.BooleanField(default=True)),
                ('respawn_timer', models.IntegerField(default=300)),
                ('last_npc_spawn', models.DateTimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='rooms', to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=25)),
                ('hp', models.IntegerField(default=100)),
                ('hp_max', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=20)),
                ('mana_max', models.IntegerField(default=20)),
                ('str_stat', models.IntegerField(default=10)),
                ('int_stat', models.IntegerField(default=10)),
                ('wil_stat', models.IntegerField(default=10)),
                ('agi_stat', models.IntegerField(default=10)),
                ('hea_stat', models.IntegerField(default=10)),
                ('cha_stat', models.IntegerField(default=10)),
                ('stat_points', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('race', models.CharField(max_length=50)),
                ('game_class', models.CharField(max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('karma', models.IntegerField(default=0)),
                ('addiction_points', models.IntegerField(default=0)),
                ('withdrawal_timer', models.IntegerField(default=0)),
                ('stalk_count', models.IntegerField(default=0)),
                ('inventory', models.ManyToManyField(through='game.InventoryItem', to='game.item')),
                ('last_combat_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalking_players', to='game.npc')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room'),
        ),
        migrations.AddField(
            model_name='item',
            name='warp_to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warp_items', to='game.room'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
