# Generated by Django 4.2.18 on 2026-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('total_rooms', models.IntegerField(default=0)),
                ('total_npcs', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='heal_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='npc_type',
            field=models.CharField(default='drone', max_length=50),
        ),
        migrations.AddField(
            model_name='npc',
            name='respawnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_npc_spawn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='map_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='map_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='respawn_npcs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='respawn_timer',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='room',
            name='theme',
            field=models.CharField(default='urban', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='zone',
            field=models.CharField(default='hub', max_length=100),
        ),
    ]
