# Generated by Django 4.2.18 on 2026-06-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameworld_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addiction_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='element',
            field=models.CharField(default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='warp_to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warp_items', to='game.room'),
        ),
        migrations.AddField(
            model_name='npc',
            name='element',
            field=models.CharField(default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='resistance',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='weakness',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='addiction_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_combat_npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalking_players', to='game.npc'),
        ),
        migrations.AddField(
            model_name='player',
            name='stalk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='withdrawal_timer',
            field=models.IntegerField(default=0),
        ),
    ]
