# Generated by Django 4.2.18 on 2026-07-19 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_player_deaths"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="stalk_count",
        ),
    ]
